/**
 * The common-password list, and the substitutions people use to disguise one.
 *
 * GENERATED FILE — do not edit. Run `python scripts/make_common_passwords.py` in `backend`
 * after changing `app/modules/auth/passwords.py`.
 *
 * The algorithm that uses this lives in `commonPasswords.ts`, hand-written so it can be
 * reviewed like any other code. `commonPasswords.test.ts` checks it against a fixture of
 * answers produced by the Python, so the two cannot quietly disagree.
 */

/** Characters people substitute to satisfy a symbol rule without changing the word. */
export const LEET: Record<string, string> = {
  "@": "a",
  "4": "a",
  "8": "b",
  "(": "c",
  "3": "e",
  "6": "g",
  "9": "g",
  "1": "i",
  "!": "i",
  "|": "i",
  "0": "o",
  "5": "s",
  $: "s",
  "7": "t",
  "+": "t",
  "2": "z",
};

export const COMMON_PASSWORDS: ReadonlySet<string> = new Set([
  "00000000",
  "11111111",
  "112233",
  "121212",
  "123123123",
  "123321",
  "123456",
  "1234567",
  "12345678",
  "123456789",
  "1234567890",
  "654321",
  "666666",
  "696969",
  "777777",
  "888888",
  "987654321",
  "999999",
  "abcdef",
  "abcdefg",
  "abcdefgh",
  "academy",
  "access",
  "aditya",
  "admin",
  "adminadmin",
  "administrator",
  "akash",
  "amanda",
  "ananya",
  "andrew",
  "angel",
  "ankit",
  "anthony",
  "arjun",
  "arsenal",
  "asdfgh",
  "asdfghjkl",
  "ashley",
  "autumn",
  "azerty",
  "babygirl",
  "bajrangbali",
  "bangalore",
  "barcelona",
  "baseball",
  "basketball",
  "batman",
  "bharat",
  "bollywood",
  "buster",
  "butterfly",
  "chaiwala",
  "changeme",
  "charlie",
  "cheese",
  "chelsea",
  "chennai",
  "chocolate",
  "classroom",
  "coaching",
  "college",
  "computer",
  "contrasena",
  "cricket",
  "daniel",
  "darling",
  "deepak",
  "default",
  "delhi",
  "demodemo",
  "dhoni",
  "dhruv",
  "dhruvacademy",
  "dhruvonline",
  "dhruvonlineacademy",
  "dilwale",
  "dosti",
  "dragon",
  "education",
  "exam",
  "example",
  "faculty",
  "family",
  "father",
  "flower",
  "football",
  "forever",
  "freedom",
  "ganesh",
  "ganesha",
  "guest",
  "hanuman",
  "harley",
  "hunter",
  "hyderabad",
  "iloveyou",
  "india",
  "indian",
  "institute",
  "internet",
  "iqazzwsx",
  "iqzwderf",
  "jaishreeram",
  "jennifer",
  "jessica",
  "jordan",
  "joshua",
  "kavita",
  "kohli",
  "kolkata",
  "krishna",
  "learning",
  "letmein",
  "library",
  "liverpool",
  "login",
  "lovely",
  "manager",
  "manchester",
  "manish",
  "master",
  "matthew",
  "michael",
  "mohabbat",
  "monkey",
  "mother",
  "mumbai",
  "mypassword",
  "namaste",
  "neha",
  "newpass",
  "nicole",
  "ninja",
  "omnamahshivaya",
  "onlineacademy",
  "passord",
  "passpass",
  "password",
  "passwort",
  "pokemon",
  "pooja",
  "prakash",
  "princess",
  "priya",
  "pyaar",
  "qazwsx",
  "qweasdzxc",
  "qwerty",
  "qwertyuiop",
  "qwertz",
  "radhekrishna",
  "rahul",
  "rainbow",
  "rajesh",
  "ranger",
  "ravi",
  "realmadrid",
  "result",
  "robert",
  "rohan",
  "rohit",
  "root",
  "rootroot",
  "sachin",
  "saibaba",
  "salman",
  "samantha",
  "sample",
  "sandbox",
  "sandeep",
  "sanjay",
  "school",
  "secret",
  "service",
  "shadow",
  "shahrukh",
  "shiva",
  "shivam",
  "sneha",
  "soccer",
  "spiderman",
  "starwars",
  "student",
  "students",
  "summer",
  "sunflower",
  "sunita",
  "sunshine",
  "superman",
  "support",
  "suresh",
  "sweetie",
  "teacher",
  "teachers",
  "temporary",
  "temppass",
  "tendulkar",
  "testing",
  "testtest",
  "thomas",
  "tigger",
  "toor",
  "trustme",
  "trustno",
  "university",
  "vijay",
  "vikram",
  "virat",
  "vishal",
  "wallet",
  "welcome",
  "whatever",
  "winter",
  "yourpassword",
  "zxcvbn",
  "zxcvbnm",
]);
