"""Async SQLAlchemy engine, session factory, declarative base and shared column mixins.

One session per request. Services commit at the end of a use case; the dependency rolls
back whatever is left. Relationships default to ``lazy="raise"`` so an accidental lazy load
fails loudly at development time instead of emitting a surprise query per row.
"""

from __future__ import annotations

import uuid
from collections.abc import AsyncGenerator
from datetime import datetime
from typing import Any

from sqlalchemy import DateTime, MetaData, String, func, text
from sqlalchemy.dialects.postgresql import UUID as PgUUID
from sqlalchemy.ext.asyncio import (
    AsyncEngine,
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from app.core.config import settings

# Explicit naming convention so Alembic autogenerate produces stable constraint names
# and a later migration can always address a constraint by name.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

# Reused column types. Lengths are deliberate: unbounded text invites abuse and
# makes index size unpredictable.
Uuid = PgUUID(as_uuid=True)
ShortStr = String(120)
MediumStr = String(255)
CodeStr = String(40)


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    def __repr__(self) -> str:  # pragma: no cover - debugging aid only
        ident = getattr(self, "id", None)
        return f"<{type(self).__name__} {ident}>"


class UuidPkMixin:
    """UUID primary key generated by PostgreSQL, so inserts never need a round trip."""

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid, primary_key=True, server_default=text("gen_random_uuid()")
    )


class TimestampMixin:
    """``created_at`` / ``updated_at`` on every table (database rules)."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


def build_engine(url: str | None = None, **overrides: Any) -> AsyncEngine:
    """Engine with a bounded pool.

    ``pool_pre_ping`` costs one cheap round trip per checkout and avoids the stale
    connection errors that managed Postgres providers cause when they recycle sockets.
    """
    options: dict[str, Any] = {
        "echo": settings.db_echo,
        "pool_size": settings.db_pool_size,
        "max_overflow": settings.db_max_overflow,
        "pool_recycle": settings.db_pool_recycle_seconds,
        "pool_pre_ping": True,
    }
    options.update(overrides)
    return create_async_engine(url or settings.database_url, **options)


engine = build_engine()
SessionLocal = async_sessionmaker(engine, expire_on_commit=False, autoflush=False)


async def get_db() -> AsyncGenerator[AsyncSession]:
    """One session per request.

    ``expire_on_commit=False`` keeps ORM objects usable after the service commits, which
    avoids a second SELECT just to serialise the response.
    """
    async with SessionLocal() as session:
        try:
            yield session
        except Exception:
            await session.rollback()
            raise
